Milestone 1: Html structure for youtube web-page
jcy2704/Youtube-HTML pull request #1
Opened 2020-09-16 15:10 UTC by alejandrotoledoweb

Added html structure with 3 sections and css for those 3 sections for the copy of youtube webpage

2020-09-16 16:56 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
#### Hey guys, your project looks amazing in terms of good practices (CSS, Semantic HTML, and so on), but you guys can improve the layout because currently, your page isn't looking like a clone.
- [x] Improve the recommended videos section.
- [x] Improve the video description section.
![image](https://user-images.githubusercontent.com/56762529/93368029-a3a6a880-f84d-11ea-83f7-e1893b73ca46.png)
### Take those images as example:
- Yours
![image](https://user-images.githubusercontent.com/56762529/93368610-80c8c400-f84e-11ea-9050-a40cbc054002.png)
- Original
![image](https://user-images.githubusercontent.com/56762529/93368923-e6b54b80-f84e-11ea-8339-b005fd1c752e.png)


## [OPTIONAL CHANGES]
- [x] Implement the comments section


## Please make the required changes and resubmit for a new code review once you are ready💪

It was a pleasure to review your code! 
<img src="https://media3.giphy.com/media/fWfowxJtHySJ0SGCgN/giphy.gif">

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-16 23:12 UTC, teekaytech requested changes
# Status: Changes required :recycle: 

### Hello team :wave: , you've done an amazing job on this project so far :muscle: :clap: , you just have to implement the finishing touches to get it approved. Kindly fix the required changes listed below:

**[ REQUIRED CHANGES]**

- [x] Update your readme file
- The getting started section needs to be changed. You have to modify that content to suit the context of your project.
- Check carefully for any other necessary adjustment(s)
- Add a live demo link of your project to your readme file. [This website](
https://raw.githack.com/) might help

**[GENERAL]**

- [ ] In your index.html, the `<body>` tag is missing. 
- This is semantically wrong. Try to understand Semantic HTML from [here](https://www.w3schools.com/html/html5_semantic_elements.asp)
![10](https://user-images.githubusercontent.com/26856491/93401296-c2229900-f879-11ea-9f9c-a7a965d16eac.png)

**[OPTIONAL]**

- [ ] Try to implement the footer section of the page.

* * *
### Kindly make these changes and request for another review.

**Best Regards,
Taofeek Olalere
GitHub: @teekaytech
Slack: @taofeekolalere**

2020-09-16 23:55 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-17 00:10 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @jcy2704 AND @alejandrotoledoweb 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes.
- [ ] Remove the inline styling and use it by the external style sheet. ([Article for support](https://speckyboy.com/good-bad-css-practices/) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright))

- **Explanation:** Inline styling is a bad practice, we recommend to use CSS in external style sheet. I provide a link for your better understanding

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-17 00:10 UTC, umairarshadbutt commented on index.html
> +                <h2 style="font-size: 25px; margin-bottom: 5px;">Embed Videos and playlists</h2>
Remove inline style and manage it in external style sheet

2020-09-17 00:10 UTC, umairarshadbutt commented on index.html
> +                <div style="display: flex; width: 90px;">
Remove inline style and manage it in the external style sheet

2020-09-17 00:10 UTC, umairarshadbutt commented on index.html
> +                        <p style="font-size: 14px; margin-top: 0px;">8,04 M Subscribers</p>
Remove inline style and manage it in the external style sheet

2020-09-17 00:52 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All of the required changes were met, this is approved!! you may carry on team!!
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-09-17 01:29 UTC, merged